In [1]:
import numpy as np

In [2]:
ls = [10,20,30,40]

In [3]:
np.array(ls) + 2

array([12, 22, 32, 42])

In [4]:
np.arange(2,18,3)

array([ 2,  5,  8, 11, 14, 17])

In [10]:
np.linspace(2,18,5)

array([ 2.,  6., 10., 14., 18.])

In [14]:
ar = np.zeros((3,4,5))

In [18]:
ar.size

60

In [24]:
ar.reshape(5,2,2,3)

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [69]:
ar = np.random.randint(2,8,(3,4,5))

In [74]:
ar

array([[[6, 2, 3, 3, 3],
        [5, 6, 4, 2, 2],
        [5, 6, 6, 4, 6],
        [3, 7, 5, 7, 3]],

       [[2, 6, 4, 3, 2],
        [4, 5, 2, 5, 2],
        [4, 6, 5, 2, 7],
        [6, 2, 5, 7, 6]],

       [[2, 5, 3, 4, 3],
        [5, 3, 7, 5, 4],
        [6, 7, 5, 5, 3],
        [2, 3, 2, 3, 6]]])

In [76]:
np.sum(ar)

256

In [77]:
np.sum(ar, axis=2)

array([[17, 19, 27, 25],
       [17, 18, 24, 26],
       [17, 24, 26, 16]])

In [18]:
ar = np.random.randint(11,99,(4,3))

In [19]:
ar

array([[58, 53, 12],
       [27, 27, 26],
       [54, 65, 59],
       [42, 64, 58]])

In [23]:
ar[1:4,1]

array([27, 65, 64])

In [24]:
ar[1:4][1]

array([54, 65, 59])

In [26]:
ar[ar>50]

array([58, 53, 54, 65, 59, 64, 58])

In [27]:
np.where(ar>50)

(array([0, 0, 2, 2, 2, 3, 3], dtype=int64),
 array([0, 1, 0, 1, 2, 1, 2], dtype=int64))

In [28]:
ar

array([[58, 53, 12],
       [27, 27, 26],
       [54, 65, 59],
       [42, 64, 58]])

In [37]:
ar.flatten()

array([58, 53, 12, 27, 27, 26, 54, 65, 59, 42, 64, 58])

In [63]:
np.append(ar, np.ones((1,3)), axis=0)

array([[58., 53., 12.],
       [27., 27., 26.],
       [54., 65., 59.],
       [42., 64., 58.],
       [ 1.,  1.,  1.]])

In [57]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [65]:
ar.shape

(4, 3)

In [74]:
ar

array([[58, 53, 12],
       [27, 27, 26],
       [54, 65, 59],
       [42, 64, 58]])

In [81]:
ar + np.zeros((4,3))

array([[58., 53., 12.],
       [27., 27., 26.],
       [54., 65., 59.],
       [42., 64., 58.]])

In [82]:
ar

array([[58, 53, 12],
       [27, 27, 26],
       [54, 65, 59],
       [42, 64, 58]])

In [90]:
np.hstack([ar, np.zeros((4,2))])

array([[58., 53., 12.,  0.,  0.],
       [27., 27., 26.,  0.,  0.],
       [54., 65., 59.,  0.,  0.],
       [42., 64., 58.,  0.,  0.]])

In [112]:
ar

array([[58., 53., 12.],
       [27., 27., 26.],
       [54., 65., 59.],
       [42., 64., 58.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 3.,  3.,  3.]])

In [126]:
ar = np.delete(ar,4, axis=0)

In [127]:
ar

array([[58., 53., 12.],
       [27., 27., 26.],
       [54., 65., 59.],
       [42., 64., 58.]])

In [128]:
zr = np.zeros((1,3))
for k in range(3):
    ar = np.vstack([ar, zr+k])
    print(ar)

[[58. 53. 12.]
 [27. 27. 26.]
 [54. 65. 59.]
 [42. 64. 58.]
 [ 0.  0.  0.]]
[[58. 53. 12.]
 [27. 27. 26.]
 [54. 65. 59.]
 [42. 64. 58.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
[[58. 53. 12.]
 [27. 27. 26.]
 [54. 65. 59.]
 [42. 64. 58.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]]


In [129]:
ar

array([[58., 53., 12.],
       [27., 27., 26.],
       [54., 65., 59.],
       [42., 64., 58.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.]])

In [131]:
ar.T

array([[58., 27., 54., 42.,  0.,  1.,  2.],
       [53., 27., 65., 64.,  0.,  1.,  2.],
       [12., 26., 59., 58.,  0.,  1.,  2.]])

In [132]:
ar1 = np.random.randint(1,10,(3,4))

In [133]:
ar2 = np.random.randint(1,10,(4,2))

In [140]:
ar1

array([[6, 3, 2, 1],
       [7, 4, 7, 4],
       [4, 7, 2, 7]])

In [143]:
ar2

array([[8, 3],
       [5, 3],
       [7, 9],
       [3, 4]])

In [139]:
np.dot(ar1,ar2)

array([[ 80,  49],
       [137, 112],
       [102,  79]])