# Basic numpy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [ ]:
The elements are all of the same type, referred to as the array dtype
The rank of the array is the number of dimensions.
The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
1D array, 2D array, ndarray, vector, matrix

In [ ]:
!pip install numpy

# To create a basic array 

#np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype



In [ ]:
# shape and size of the array
ndarray.ndim, ndarray.size, ndarray.shape

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array

In [ ]:
import numpy as np

In [ ]:
arr = [10,15,16,17,18,19,18,12,20]

In [ ]:
arr.astype('str')

In [ ]:
print(type(arr))
print(arr)

In [ ]:
arr = np.array(arr) 
print(arr)
print(type(arr))

In [ ]:
arr 

In [ ]:
arr3 = [[10,15,16,17,18,19,18,12,20]]

In [ ]:
arr3 = np.array(arr3)
arr3.ndim

In [ ]:
arr.ndim, arr.size, arr.shape, arr.view(),arr.min(), arr.max()

In [ ]:
arr.mean(), arr.var(),arr.prod(), arr.sum(),arr.std()

In [ ]:
any(arr) is int

In [ ]:
# two dimentional
arr1 = [[10,15,3],
         [5,6,np.nan],
         [7,8,np.nan]]

In [ ]:
arr1 = np.array(arr1)

In [ ]:
arr1

In [ ]:
arr1.shape

In [ ]:
arr1.ndim,arr1.shape,arr1.size

In [ ]:
arr1.mean(), arr1.var(),arr1.prod(), arr1.sum(),arr1.std()

In [ ]:
# more than one dimensions 
arr2 = np.array([[[[1, 2]]], [[3, 4],[6,8]]]) 
print(arr2)

In [ ]:
arr2 = np.array([[[[1,0,0]],
                 [[0,0,2]],
                 [[1,5,6]]]])

In [ ]:
arr2.ndim, arr2.shape

In [ ]:
arr2 = np.array([[[[1,0,0],
                   [2,5,3]],
                  
                  [[0,0,2],
                 [2,5,3]],
                  
                 [[1,5,6],
                 [2,5,3]]]])
arr2.shape

In [ ]:
arr3 = np.array([[[[1,2,3,4]],
                  [[1,2,3,4]]]])
print(arr3.ndim,arr3.shape)

In [ ]:
# array of zeros
print('array of zeros')
print(np.zeros(6))
# print()
# array of ones
print(np.ones(5))
print()
# array of stdout
print(np.empty(10))
print()
# array of given range and number of values.
print(np.linspace(1,10, num=30))

# np.arange()

In [ ]:
print(range(10,20))
for i in range(10,21):
    print(i)

In [ ]:
d = np.arange(1,21)
d

In [ ]:
# dtype of array is int8 (1 byte) 
x = np.array(d,dtype = 'int64')
print(x.itemsize)
print(x.dtype)

In [ ]:
# dtype of array is now float32 (4 bytes) 
x = np.array([1,2,3,4,5,6,9,10,10,12,15,14], dtype = int) 
print(x.itemsize)

# adding removing and sorting the elements
# np.sort(), np.concatenate()

In [ ]:
arr = np.array([[2, 1, 5, 3, 7, 4, 6, 8]])
np.sort(arr,axis = -1)

In [ ]:
np.sort(arr2,axis = 0)

In [ ]:
np.sort(arr2,axis = None)

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate([a,b])

In [ ]:
np.concatenate((a,b), axis=0) # column wise concatination

In [ ]:
np.concatenate([[a,b]],axis = 1) # row wise concatination

# converting to 1D to 2D array reshape,np.newaxis, np.expand_dims

In [ ]:
import numpy as np 
a = np.array([[[[1,2,3],[4,5,6]]]]) 
print(a.shape)
print(a)

In [ ]:
b = a.reshape(6,) 
print(b.ndim)

In [ ]:
a.reshape(1,1,6)

In [ ]:
a.reshape(3,2)

In [ ]:
a = np.arange(24) 
print(a)

In [ ]:
a.reshape(1,24),a.reshape(24,1),a.reshape(1,8,3)

In [ ]:
a.reshape(1,2,3,4)

In [ ]:
## now reshape it 
b = a.reshape(2,2,3,2) 
print(b)
b.ndim
# b is having three dimensions

In [ ]:
help(np.reshape)

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])
a.ndim

1

In [3]:
a2 = a[np.newaxis,5:10]
print(a2)
print(a2.ndim)

[[ 6  7  8  9 10]]
2


In [4]:
a3 = a[0:6,np.newaxis]
print(a3)
print(a3.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2


In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [6]:
b = np.expand_dims(a, axis=0)
print(b.shape)
print(b.ndim)
print(b)

(1, 6)
2
[[1 2 3 4 5 6]]


In [8]:
c = np.expand_dims(b, axis=1)
print(c)
print(c.shape)
print(c.ndim)

[[[1 2 3 4 5 6]]]
(1, 1, 6)
3


# Indexing and slicing

In [9]:
data = np.array([1, 2, 3,5,6,9,10])
print(data[1])
print(data[0:5:2])
print(data[1:])
print(data[-2:])

2
[1 3 6]
[ 2  3  5  6  9 10]
[ 9 10]


In [13]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
15 in a

False

In [37]:
data = np.array([1, 2, 3,5,6,9,10,10,9,6])

In [24]:
set(data)

{1, 2, 3, 5, 6, 9, 10}

In [25]:
np.unique(data)

array([ 1,  2,  3,  5,  6,  9, 10])

In [14]:
lst = [1 , 2, 3, 4,5, 6, 7, 8]
lst in 5

TypeError: argument of type 'int' is not iterable

In [18]:
divisible_by_2 = a[a%2 != 0]
print(divisible_by_2)

[ 1  3  5  7  9 11]


In [22]:
a[(a>5) & (a<12) & (a>=10)]

array([10, 11])

In [28]:
a[np.logical_and((a>5),(a<12))]

array([ 6,  7,  8,  9, 10, 11])

In [31]:
a[np.logical_or((a>5),(a<12),(a!=10))]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
c = a[(a > 5) & (a < 8)]
print(c)

[6 7]


In [33]:
five_up = (a <= 5) & (a != 5)
print(a[five_up])

[1 2 3 4]


In [ ]:
a

In [ ]:
a[2],a[1]

In [ ]:
list_of_coordinates= zip(a[2], a[1])
for coord in list_of_coordinates:
    print(coord)

In [ ]:
list_of_coordinates

In [35]:
a = np.zeros([5,6])
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
not_there = np.nonzero([data])
print(not_there)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))


# # Element-wise Operation	Operator	Function
Addition	+	add()
Subtraction	-	subtract()
Multiplication	*	multiply()
Division	/	divide()
Exponentiation	**	power()
Modulus	%	mod()

In [40]:
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print(result1)

# using the add() function
result2 = np.add(first_array, second_array)
print(result2)


[ 3  7 11 15]
[ 3  7 11 15]


In [41]:
 #using the - operator
result1 = first_array - second_array
print("Using the - operator:",result1) 

# using the subtract() function
result2 = np.subtract(first_array, second_array)
print("Using the subtract() function:",result2) 

Using the - operator: [-1 -1 -1 -1]
Using the subtract() function: [-1 -1 -1 -1]


In [42]:
# using the * operator
result1 = first_array * second_array
print("Using the * operator:",result1) 

# using the multiply() function
result2 = np.multiply(first_array, second_array)
print("Using the multiply() function:",result2) 

Using the * operator: [ 2 12 30 56]
Using the multiply() function: [ 2 12 30 56]


In [43]:
# using the / operator
result1 = first_array / second_array
print("Using the / operator:",result1) 

# using the divide() function
result2 = np.divide(first_array, second_array)
print("Using the divide() function:",result2) 

Using the / operator: [0.5        0.75       0.83333333 0.875     ]
Using the divide() function: [0.5        0.75       0.83333333 0.875     ]


In [44]:
# using the ** operator
array1 = np.array([1, 3, 5, 7])
result1 = array1 ** 2
print("Using the ** operator:",result1) 

# using the power() function
result2 = np.power(array1, 3)
print("Using the power() function:",result2) 

Using the ** operator: [ 1  9 25 49]
Using the power() function: [  1  27 125 343]


In [45]:
# using the % operator
result1 = first_array % second_array
print("Using the % operator:",result1) 

# using the mod() function
result2 = np.mod(first_array, second_array)
print("Using the mod() function:",result2)

Using the % operator: [1 3 5 7]
Using the mod() function: [1 3 5 7]


In [46]:
import numpy as np
first_array = np.array([[1, 3, 5, 7],
                        [5,4,8,9]])
print(first_array)

print('np.transpose')
print(np.transpose(first_array))

print('array.transpose()')
print(first_array.transpose())

print('array.T')
print(first_array.T)

[[1 3 5 7]
 [5 4 8 9]]
np.transpose
[[1 5]
 [3 4]
 [5 8]
 [7 9]]
array.transpose()
[[1 5]
 [3 4]
 [5 8]
 [7 9]]
array.T
[[1 5]
 [3 4]
 [5 8]
 [7 9]]


In [ ]:
Array Operations------>Functions
Array Creation Functions------>np.array(), np.zeros(), np.ones(), np.empty(), np.nonzeros()etc.
Array Manipulation Functions------>np.reshape(), np.transpose(), etc.
Array Mathematical Functions------>np.add(), np.subtract(), np.sqrt(), np.power(), etc.
Array Statistical Functions------>np.median(), np.mean(), np.std(), and np.var().
Array Input and Output Functions------>np.save(), np.load(), np.loadtxt(), etc.

In [ ]:

Operators	Descriptions
< (less than)	returns True if element of the first array is less than the second one
<= (less than or equal to)	returns True if element of the first array is less than or equal to the second one
> (greater than)	returns True if element of the first array is greater than the second one
>= (greater than or equal to)	returns True if element of the first array is greater than or equal to the second one
== (equal to)	returns True if the element of the first array is equal to the second one
!= (not equal to)	returns True if the element of the first array is not equal to the second one

Functions	Descriptions
less()	returns element-wise True if the first value is less than the second
less_equal()	returns element-wise True if the first value is less than or equal to second
greater()	returns element-wise True if the first value is greater then second
greater_equal()	returns element-wise True if the first value is greater than or equal to second
equal()	returns element-wise True if two values are equal
not_equal()	returns element-wise True if two values are not equal

In [ ]:
Logical Operators	Descriptions
logical_and	Computes the element-wise truth value of x1 AND x2 &
logical_or	Computes the element-wise truth value of x1 OR x2 |
logical_not	Computes the element-wise truth value of NOT x !=

In [ ]:
import numpy as np

x1 = np.array([True, False, True])
x2 = np.array([False, False, True])

# Logical AND
print(np.logical_and(x1, x2)) # Output: [False False  True]

# Logical OR
print(np.logical_or(x1, x2)) # Output: [ True False  True]

# Logical NOT
print(np.logical_not(x1)) # Output: [False  True False]

In [ ]:
Trigonometric Function	Computes (in radians)
sin()	the sine of an angle
cos()	cosine of an angle
tan()	tangent of an angle
arcsin()	the inverse sine
arccos()	the inverse cosine
arctan()	the inverse tangent
degrees()	converts an angle in radians to degrees
radians()	converts an angle in degrees to radians

In [49]:
import numpy as np
# define an angle in radians
angle =  2
print("Initial angle in radian:", angle)

# convert the angle to degrees
angle_degree = np.degrees(angle)
print("Angle in degrees:", angle_degree)

# convert the angle back to radians
angle_radian = np.radians(angle_degree)
print("Angle in radians (after conversion):", angle_radian)

Initial angle in radian: 2
Angle in degrees: 114.59155902616465
Angle in radians (after conversion): 2.0


In [48]:
import numpy as np
# array of angles in radians
angles = np.array([0, 1, 0.9])
print("Angles:", angles)

# compute the sine of the angles: sine = opp/hyp, cos = adj / hyp, tan = opp/adj
sine_values = np.sin(angles)
print("Sine values:", sine_values)

# compute the inverse sine of the angles
inverse_sine = np.arcsin(angles)
print("Inverse Sine values:", inverse_sine)

Angles: [0.  1.  0.9]
Sine values: [0.         0.84147098 0.78332691]
Inverse Sine values: [0.         1.57079633 1.11976951]


In [50]:
array = np.array([[10,20,30,40,50],
                  [15,18,19,17,20],
                  [12,17,18,19,16]])

In [51]:
# rows wise mean calculation
array.mean(axis = 1)

array([30. , 17.8, 16.4])

In [52]:
# column wise mean calculation
array.mean(axis = 0)

array([12.33333333, 18.33333333, 22.33333333, 25.33333333, 28.66666667])

In [56]:
import numpy as np
# create a numpy array
array = np.array([[10,20,30,40,50],
                  [15,18,19,17,20],
                  [12,17,18,19,16]])

# compute the mean of marks
mean_marks = np.mean(array,axis = 1)
print("Mean:",mean_marks)

# compute the median of marks
median_marks = np.median(array,axis = 1)
print("Median:",median_marks)

# find the minimum and maximum marks
min_marks = np.min(array,axis = 1)
print("Minimum marks:", min_marks)

max_marks = np.max(array,axis = 1)
print("Maximum marks:", max_marks)

Q1_marks = np.quantile(array,0.25,axis = 1)
print('Q1:',Q1_marks)

Q2_marks = np.quantile(array,0.50,axis = 1)
print('Q2:',Q2_marks)

Q3_marks = np.quantile(array,0.75,axis = 1)
print('Q3;',Q3_marks)

P3_marks = np.percentile(array,75,axis = 1)
print('P3:',P3_marks)

Mean: [30.  17.8 16.4]
Median: [30. 18. 17.]
Minimum marks: [10 15 12]
Maximum marks: [50 20 19]
Q1: [20. 17. 16.]
Q2: [30. 18. 17.]
Q3; [40. 19. 18.]
P3: [40. 19. 18.]


In [ ]:
Q1 = np.quantile('salary',0.25)
Q3 = np.quantile('salary',0.75)
IQR = (Q3 - Q1) /2
rangeIQR = (Q3 +- 1.5*IQR)

In [ ]:
print(np.exp(1))
print(np.pi)

In [ ]:
Rounding Functions	Functions
round()	returns the value rounded to the desired precision
floor()	returns the values of array down to the nearest integer that is less than each element
ceil()	returns the values of array up to the nearest integer that is greater than each element.

In [57]:
import numpy as np
numbers = np.array([1.23456, 2.34567, 3.45678, 4.56789])
# round the array to two decimal places
rounded_array = np.round(numbers,1)
print(rounded_array)

[1.2 2.3 3.5 4.6]


In [58]:
array1 = np.array([1.23456, 2.34567, 3.45678, 4.56789])
print("Array after floor():", np.floor(array1))
print("Array after ceil():", np.ceil(array1))

Array after floor(): [1. 2. 3. 4.]
Array after ceil(): [2. 3. 4. 5.]


In [ ]:
Numpy Constants
In Numpy, the most commonly used constants are pi and e

In [59]:
import numpy as np
radius = 2
circumference = 2 * np.pi * radius
print(circumference)

y = np.e
print(y)
print(np.pi)

12.566370614359172
2.718281828459045
3.141592653589793


In [63]:
1/2.718

0.36791758646063283

In [62]:
y = np.exp(-1)
print(y)

0.36787944117144233


In [ ]:
String function
Functions	Descriptions
add()	concatenates two strings
multiply()	repeats a string for a specified number of times
capitalize()	capitalizes the first letter of a string
lower()	converts all uppercase characters in a string to lowercase
upper()	converts all lowercase characters in a string to uppercase
joins()	joins a sequence of strings
equalin(()	checks if two strings are equal or not

In [64]:
array1 = np.array(['iPhone: ', 'price: '])
array2 = np.array(['15', '$900'])
# perform element-wise array string concatenation
result = np.char.add(array1, array2)
print(result)

['iPhone: 15' 'price: $900']


In [65]:
# define array with three string elements
array1 = np.array(['A', 'B', 'C']) 
#  repeat each element in array1 two times 
result = np.char.multiply(array1, 3)  
print(result)  

['AAA' 'BBB' 'CCC']


In [66]:
# define an array with three string elements
array1 = np.array(['eric', 'paul', 'sean'])  
# capitalize the first letter of each string in array1 
result = np.char.capitalize(array1)  
print(result)

['Eric' 'Paul' 'Sean']


In [67]:
array1 = np.array(['nEpalI', 'AmeriCAN', 'CaNadIan'])
# convert all string elements to uppercase
result1 = np.char.upper(array1)
# convert all string elements to lowercase
result2 = np.char.lower(array1)
print("To Uppercase: ",result1)
print("To Lowercase: ",result2)

To Uppercase:  ['NEPALI' 'AMERICAN' 'CANADIAN']
To Lowercase:  ['nepali' 'american' 'canadian']


In [68]:
import numpy as np
# create an array of strings
array1 = np.array(['hello', 'world'])
# join the strings in the array using a dash as the delimiter
result = np.char.join('*', array1)
print(result)

['h*e*l*l*o' 'w*o*r*l*d']


In [70]:
import numpy as np
# create two arrays of strings
array1 = np.array(['C', 'Python', 'Swift'])
array2 = np.array(['C', 'python', 'Java'])
# check if each element of the arrays is equal
result = np.char.equal(array1, array2)
print(result)

[ True False False]


In [ ]:
import numpy as np

# 1-D array
array1 = np.array([1, 2, 3])

# scalar
number = 5

# add scalar and 1-D array
sum = array1 + number

print(sum)

In [ ]:
# transformation and file opeartion

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"D:\DS-Batch1\DS dataset\Salaries.csv")
df2 = df[['salary','phd']].values

In [3]:
df2

array([[ 57800,     51],
       [ 62884,     25],
       [ 63100,      7],
       [ 71065,     12],
       [ 72500,      2],
       [ 72500,      3],
       [ 73000,      4],
       [ 73300,     26],
       [ 73500,      5],
       [ 74692,     11],
       [ 74830,     13],
       [ 75044,      8],
       [ 77000,      5],
       [ 77500,     10],
       [ 77500,      4],
       [ 78500,      8],
       [ 80225,      4],
       [ 81285,     20],
       [ 85000,      2],
       [ 88000,      1],
       [ 90450,     17],
       [ 91000,      4],
       [ 91000,     29],
       [ 91100,     30],
       [ 91300,      7],
       [ 92000,      4],
       [ 92000,      4],
       [ 92000,      3],
       [ 93000,     12],
       [ 94350,     29],
       [ 97032,     10],
       [ 99418,     35],
       [102000,     20],
       [103106,     33],
       [103275,     27],
       [103613,     11],
       [103750,     13],
       [103994,     12],
       [104542,     19],
       [104800,     20],


In [4]:
log_salry = np.log(df2)
log_salry

array([[10.96474405,  3.93182563],
       [11.04904704,  3.21887582],
       [11.05247605,  1.94591015],
       [11.17135023,  2.48490665],
       [11.19134184,  0.69314718],
       [11.19134184,  1.09861229],
       [11.19821472,  1.38629436],
       [11.20231589,  3.25809654],
       [11.20504069,  1.60943791],
       [11.22112827,  2.39789527],
       [11.22297415,  2.56494936],
       [11.22582989,  2.07944154],
       [11.2515607 ,  1.60943791],
       [11.25803322,  2.30258509],
       [11.25803322,  1.38629436],
       [11.2708539 ,  2.07944154],
       [11.29259047,  1.38629436],
       [11.30571678,  2.99573227],
       [11.35040654,  0.69314718],
       [11.38509209,  0.        ],
       [11.41255249,  2.83321334],
       [11.41861479,  1.38629436],
       [11.41861479,  3.36729583],
       [11.41971308,  3.40119738],
       [11.42190607,  1.94591015],
       [11.42954386,  1.38629436],
       [11.42954386,  1.38629436],
       [11.42954386,  1.09861229],
       [11.44035477,

In [6]:
import os
os.listdir()

['.ipynb_checkpoints',
 'countries.csv',
 'country.csv',
 'country1.csv',
 'country3.csv',
 'couuntry.csv',
 'data.csv',
 'Deep_learning',
 'file.csv',
 'file.npz',
 'file1.csv',
 'file1.npy',
 'file2.npz',
 'Intermediate Numpy .ipynb',
 'intermediate Python.ipynb',
 'Introduction to python-Copy1.ipynb',
 'Introduction_to_python.ipynb',
 'losalry.npy',
 'Marks.csv',
 'Matplotlib and Seaborn.ipynb',
 'newfile.txt',
 'newfile1.txt',
 'Python Interview Questions.docx',
 'Python matplotlib library.ipynb',
 'Python Numpy  library.ipynb',
 'Python Pandas library.ipynb',
 'Python pandas numpy .ipynb',
 'Python_interview_questions.ipynb',
 'results.csv',
 'Results1.csv',
 'testfile',
 'testfile5',
 'USERDATA.csv',
 'users_data.csv',
 'users_data.txt']

In [7]:
np.savetxt('salary.txt', log_salry)

In [8]:
# # # # load the data from the text file and print the loaded data
loaded_data = np.loadtxt('salary.txt') 
print(loaded_data)

[[10.96474405  3.93182563]
 [11.04904704  3.21887582]
 [11.05247605  1.94591015]
 [11.17135023  2.48490665]
 [11.19134184  0.69314718]
 [11.19134184  1.09861229]
 [11.19821472  1.38629436]
 [11.20231589  3.25809654]
 [11.20504069  1.60943791]
 [11.22112827  2.39789527]
 [11.22297415  2.56494936]
 [11.22582989  2.07944154]
 [11.2515607   1.60943791]
 [11.25803322  2.30258509]
 [11.25803322  1.38629436]
 [11.2708539   2.07944154]
 [11.29259047  1.38629436]
 [11.30571678  2.99573227]
 [11.35040654  0.69314718]
 [11.38509209  0.        ]
 [11.41255249  2.83321334]
 [11.41861479  1.38629436]
 [11.41861479  3.36729583]
 [11.41971308  3.40119738]
 [11.42190607  1.94591015]
 [11.42954386  1.38629436]
 [11.42954386  1.38629436]
 [11.42954386  1.09861229]
 [11.44035477  2.48490665]
 [11.45476655  3.36729583]
 [11.4827961   2.30258509]
 [11.50708846  3.55534806]
 [11.53272809  2.99573227]
 [11.54351286  3.49650756]
 [11.54515061  3.29583687]
 [11.54841808  2.39789527]
 [11.54973944  2.56494936]
 

In [9]:
# save the array to a file
np.save('losalry.npy', log_salry)
# load the saved NumPy array

In [10]:
loaded_array = np.load('losalry.npy')
# # display the loaded array
print(loaded_array)

[[10.96474405  3.93182563]
 [11.04904704  3.21887582]
 [11.05247605  1.94591015]
 [11.17135023  2.48490665]
 [11.19134184  0.69314718]
 [11.19134184  1.09861229]
 [11.19821472  1.38629436]
 [11.20231589  3.25809654]
 [11.20504069  1.60943791]
 [11.22112827  2.39789527]
 [11.22297415  2.56494936]
 [11.22582989  2.07944154]
 [11.2515607   1.60943791]
 [11.25803322  2.30258509]
 [11.25803322  1.38629436]
 [11.2708539   2.07944154]
 [11.29259047  1.38629436]
 [11.30571678  2.99573227]
 [11.35040654  0.69314718]
 [11.38509209  0.        ]
 [11.41255249  2.83321334]
 [11.41861479  1.38629436]
 [11.41861479  3.36729583]
 [11.41971308  3.40119738]
 [11.42190607  1.94591015]
 [11.42954386  1.38629436]
 [11.42954386  1.38629436]
 [11.42954386  1.09861229]
 [11.44035477  2.48490665]
 [11.45476655  3.36729583]
 [11.4827961   2.30258509]
 [11.50708846  3.55534806]
 [11.53272809  2.99573227]
 [11.54351286  3.49650756]
 [11.54515061  3.29583687]
 [11.54841808  2.39789527]
 [11.54973944  2.56494936]
 

In [ ]:
import os 
os.listdir()
os.remove('file.npz')

In [12]:
os.listdir()

['.ipynb_checkpoints',
 'arrayfile.npz',
 'countries.csv',
 'country.csv',
 'country1.csv',
 'country3.csv',
 'couuntry.csv',
 'data.csv',
 'Deep_learning',
 'file.csv',
 'file.npz',
 'file1.csv',
 'file1.npy',
 'file2.npz',
 'Intermediate Numpy .ipynb',
 'intermediate Python.ipynb',
 'Introduction to python-Copy1.ipynb',
 'Introduction_to_python.ipynb',
 'losalry.npy',
 'Marks.csv',
 'Matplotlib and Seaborn.ipynb',
 'newfile.txt',
 'newfile1.txt',
 'Python Interview Questions.docx',
 'Python matplotlib library.ipynb',
 'Python Numpy  library.ipynb',
 'Python Pandas library.ipynb',
 'Python pandas numpy .ipynb',
 'Python_interview_questions.ipynb',
 'results.csv',
 'Results1.csv',
 'salary.txt',
 'testfile',
 'testfile5',
 'USERDATA.csv',
 'users_data.csv',
 'users_data.txt']

In [11]:
import numpy as np
array1 = np.array([2, 6, 10]) # create two NumPy arrays
array2 = np.array([4, 8, 12])
np.savez('arrayfile.npz', file1 = array1, file2 = array2)  # save the two arrays into a single file

In [13]:
# load the saved arrays 
load_data = np.load('arrayfile.npz')
print(load_data)

In [18]:
# # retrieve the arrays using their names
load_data['file1']
array2 = load_data['file2']
# # display the loaded arrays
print(array1)
print(array2)

[ 2  6 10]
[ 4  8 12]


In [19]:
load_data['file1']

array([ 2,  6, 10])

In [16]:
load_data.files

['file1', 'file2']

# Linear algebra

In [ ]:
# NumPy Matrix Operations
Functions	Descriptions
array()	creates a matrix
dot()	performs matrix multiplication
transpose()	transposes a matrix
linalg.inv()	calculates the inverse of a matrix
linalg.det()	calculates the determinant of a matrix
flatten()	transforms a matrix into 1D array

# NumPy Linear Algebra Functions
Operators	Descriptions
dot()	calculates product of two arrays
inner()	calculates inner product of arrays
outer()	calculates outer product of arrays
det()	calculates determinant of a matrix
solve()	solves linear matrix equation
inv()	calculates the multiplicative inverse of the matrix
trace()	calculates the sum of diagonal elements

In [20]:
# create a 2x2 matrix
matrix1 = np.array([[1, 3], 
                   [5, 7]])
print("2x2 Matrix:\n",matrix1)
# create a 3x3  matrix
matrix2 = np.array([[2, 3, 5],
             	    [7, 14, 21],
                    [1, 3, 5]])
print("\n3x3 Matrix:\n",matrix2)

2x2 Matrix:
 [[1 3]
 [5 7]]

3x3 Matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


In [21]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
lower = tril(matrix2)
print(lower)
upper = triu(matrix2)
print(upper)

[[ 2  0  0]
 [ 7 14  0]
 [ 1  3  5]]
[[ 2  3  5]
 [ 0 14 21]
 [ 0  0  5]]


In [26]:
# diagonal matrix
from numpy import diag
M = array([[1, 2, 3], 
           [1, 2, 3], 
           [1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print('Diagonal values:',d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Diagonal values: [1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
# identity matrix
from numpy import identity
I = identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
#create two matrices
matrix1 = np.array([[1, 3], 
                    [5, 7]])
matrix2 = np.array([[2, 6], 
                    [4, 8]])
mult = matrix1*matrix2
print(mult)
# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)
print("matrix1 x matrix2: \n",result)

[[ 2 18]
 [20 56]]
matrix1 x matrix2: 
 [[14 30]
 [38 86]]


In [32]:
# matrix-vector multiplication
A = array([[1, 2], [3, 4], [5, 6]])
B = array([0.5, 0.5])
C = A.dot(B)
print(C)
D = A @ B
print(D)

[1.5 3.5 5.5]
[1.5 3.5 5.5]


In [33]:
# create a matrix
matrix1 = np.array([[1, 3,5,6,7],
                    [5, 7,0,1,2]])
# get transpose of matrix1
result = np.transpose(matrix1)
result_1 = matrix1.T
print(result)
print(result_1)

[[1 5]
 [3 7]
 [5 0]
 [6 1]
 [7 2]]
[[1 5]
 [3 7]
 [5 0]
 [6 1]
 [7 2]]


In [34]:
# trace of matrix (sum of diagonal values is trace.)
from numpy import trace
A = array([[1, 2, 3],  [4, 6, 6],[7, 8, 9]])
print(A)
B = trace(A)
print(B)

[[1 2 3]
 [4 6 6]
 [7 8 9]]
16


In [35]:
# find determinant of matrix1
matrix1 = np.array([[1, 2, 3], [4, 5, 1],[2, 3, 4]])
result = np.linalg.det(matrix1)
print(result)

-4.999999999999999


In [40]:
# vector rank
from numpy.linalg import matrix_rank
# rank
v1 = array([[1, 2, 3], [4, 5, 1], [0,0,0]])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([1,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[[1 2 3]
 [4 5 1]
 [0 0 0]]
2
[1 0 0 0 0]
1


In [41]:
#Flatten Matrix in NumPy
result = matrix1.flatten()
print("Flattened 2x3 matrix:", result)

Flattened 2x3 matrix: [1 2 3 4 5 1 2 3 4]


In [42]:
#NumPy Set Operations
import numpy as np
A = np.array([[1, 3, 5]])
B = np.array([0, 2, 3])
# union of two arrays
result = np.union1d(A, B)
print(result)  

[0 1 2 3 5]


In [43]:
# intersection of two arrays
result = np.intersect1d(A, B)
print(result)  

[3]


In [47]:
# difference of two arrays
result = np.setdiff1d(B,A)
print(result)  

[0 2]


In [45]:
# symmetric difference of two arrays
result = np.setxor1d(A, B)
print(result)  

[0 1 2 5]


In [46]:
array1 = np.array([1,1, 2, 2, 4, 7, 7, 3, 5, 2, 5])
# unique values from array1
result = np.unique(array1)
print(result)  

[1 2 3 4 5 7]


# Numpy Random

In [59]:
import numpy as np
# generate random integer from 0 to 9
random_number = np.random.randint(0, 2)
print(random_number)

1


In [90]:
from numpy import random as rd
random_number = rd.randint(0, 2,10)
print(random_number)

[0 0 0 1 0 0 1 0 1 1]


In [105]:
# generate random float-point number between 0 and 1
random_number = np.random.rand(10)
print(random_number)

[0.57001453 0.25792099 0.59077157 0.91899903 0.23277905 0.81470957
 0.40761232 0.08422419 0.75546455 0.57028602]


In [110]:
# generate 2D array of shape (3, 4) with random integers
result = np.random.randint(100, 1000, (3,3,4))
print("\n2D Random Integer Array:\n",result)


2D Random Integer Array:
 [[[780 303 789 675]
  [374 957 689 129]
  [425 638 111 493]]

 [[394 775 146 335]
  [921 947 645 306]
  [939 414 132 476]]

 [[215 741 691 347]
  [159 785 706 805]
  [703 168 659 352]]]


In [112]:
# create an array of integers from 1 to 5
array1 = np.array([1, 2, 3, 4, 5,6])
# choose a random number from array1
random_choice = np.random.choice(array1)
print(random_choice)

3


In [118]:
name = np.array(['data','DA','DS','ST'])
random_choice = np.random.choice(name)
print(random_choice)

ST


In [124]:
# np.random.seed(10)
data = np.random.binomial(10,0.90,size=10)
print(data)

[10  9 10  8 10 10  9  8  9  9]


In [135]:
pos_values = np.random.poisson(lam=2.4,size = 30)
pos_values

array([4, 3, 1, 4, 4, 0, 2, 6, 5, 0, 3, 1, 4, 6, 3, 0, 1, 3, 2, 0, 2, 5,
       2, 5, 3, 1, 3, 1, 2, 3])

In [136]:
np.mean(np.array([4, 3, 1, 4, 4, 0, 2, 6, 5, 0, 3, 1, 4, 6, 3, 0, 1, 3, 2, 0, 2, 5,
       2, 5, 3, 1, 3, 1, 2, 3]))

2.6333333333333333

In [137]:
norm_values = np.random.normal(25,2.5,50)
norm_values

array([24.4970883 , 27.91348061, 22.1865623 , 27.24423642, 24.43817017,
       22.63420197, 24.03707052, 28.83458676, 25.40077561, 24.86871511,
       23.22924343, 28.41484631, 27.62374122, 20.86705877, 23.8558239 ,
       26.6747668 , 25.47822742, 29.01276467, 26.40525511, 27.94110367,
       26.03034911, 28.11831038, 27.68369749, 26.20183902, 23.30923593,
       24.57255905, 25.05187462, 24.38659727, 26.41651231, 24.24855067,
       24.50370883, 23.82408728, 21.17411979, 27.44209004, 26.74816958,
       28.05581124, 23.17944809, 27.29176223, 24.60624052, 27.80727015,
       22.47593206, 24.01349462, 24.933168  , 25.88980288, 28.87792607,
       25.07165737, 19.02454513, 30.82501296, 30.57720543, 24.08994186])

In [138]:
min(norm_values), max(norm_values),np.mean(norm_values),np.std(norm_values)

(19.024545134219487, 30.825012958627536, 25.559772781390055, 2.445338483603056)

In [143]:
sampl1 = np.random.choice(norm_values,size = 45)
print(np.mean(sampl1))
print(np.std(sampl1))

25.321461590968728
2.0017785648114734


In [149]:
# interpolation
day = np.array([2, 4, 7])
gold_price = np.array([55, 58, 65])
# find the value of gold on day 3
day3_value = np.interp(13, day, gold_price)
print("The value of gold on day 3 is", day3_value)

The value of gold on day 3 is 65.0


In [150]:
import numpy as np
day = np.array([2, 4, 7, 10,11])
gold_price = np.array([55, 58, 65, 70,700])
# days whose value is to be interpolated
interpolate_days = np.array([1, 3, 5, 6, 8, 9,12])
interpolated_price= np.interp(interpolate_days, day, gold_price)
print(interpolated_price)

[55.         56.5        60.33333333 62.66666667 66.66666667 68.33333333
 70.        ]


# NumPy Date and Time

In [157]:
# get the current date and time 
result = np.datetime64('now')
today = np.datetime64('Today')
print("Current date and time:")
print(result)
print(today)

# get the current date
date_today = np.datetime64(result,'s' )

print("Today's date:")
print(date_today)

Current date and time:
2024-05-05T12:08:04
2024-05-05
Today's date:
2024-05-05T12:08:04


In [158]:
import numpy as np

# use datetime64() for different time units
year = np.datetime64('2023', 'Y')
month = np.datetime64('2023-04', 'M')
day = np.datetime64('2023-04-29', 'D')
hour = np.datetime64('2023-04-29T10', 'h')
minute = np.datetime64('2023-04-29T10:30', 'm')
second = np.datetime64('2023-04-29T10:30:15', 's')

print("Year: ", year)
print("Month: ", month)
print("Day: ", day)
print("Hour: ", hour)
print("Minute: ", minute)
print("Second: ", second)

Year:  2023
Month:  2023-04
Day:  2023-04-29
Hour:  2023-04-29T10
Minute:  2023-04-29T10:30
Second:  2023-04-29T10:30:15


In [ ]:
Convert datetime64 Objects

In [159]:
import numpy as np
from datetime import datetime

# create a datetime64 object
dt64 = np.datetime64('now')
print(dt64)
print(type(dt64))

# convert datetime64 to datetime object
dt = dt64.astype(datetime)
print(dt)

# print the datetime object
print(type(dt))

2024-05-05T12:10:30
<class 'numpy.datetime64'>
2024-05-05 12:10:30
<class 'datetime.datetime'>


In [ ]:
# Create a Range of Dates

In [166]:
import numpy as np
# create a range of dates from 2023-04-01 to 2023-04-10
dates = np.arange('2024-01-01', '2025-01-01', dtype='datetime64[Y]')
# print the dates
print(len(dates))

1


In [ ]:
Arithmetic Operations on NumPy datetime64 Objects

In [171]:
today = np.datetime64('today')             # create a datetime64 object for today
tomorrow = today + np.timedelta64(3, 'D')       # add one day to today's date
date1 = np.datetime64('2024-12-01')    # create datetime64 objects for two dates
date2 = np.datetime64('2024-01-30')
num_days = date1 - date2   # calculate the number of days between the two dates

# display the results
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)
print("Number of days between", date1, "and", date2, "is", num_days)

Today's date: 2024-05-05
Tomorrow's date: 2024-05-08
Number of days between 2024-12-01 and 2024-01-30 is 306 days


In [ ]:
tomorrow = today + np.timedelta64(24, 'h') 
print(tomorrow)

In [ ]:
# NumPy busday() Function

In [ ]:
'1111100'

In [173]:
# create datetime64 objects for two dates
date1 = np.datetime64('2024-05-01')
date2 = np.datetime64('2024-05-30')
# calculate the number of business days between the two dates
num_business_days = np.busday_count(date1, date2,weekmask='1111011',holidays=['2024-05-01','2024-05-20'])
# display the number of business days between the two dates
print("Number of business days between", date1, "and", date2, "is", num_business_days)

Number of business days between 2024-05-01 and 2024-05-30 is 23
